"""empty message

Revision ID: 0b1eb612cbc2
Revises: aa3a377f7695
Create Date: 2017-06-24 20:11:40.830731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b1eb612cbc2'
down_revision = 'aa3a377f7695'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('formula', sa.Column('user_key', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('formula', 'user_key')
    # ### end Alembic commands ###
