"""empty message

Revision ID: 1bb036aaf187
Revises: c2c69e3a858e
Create Date: 2017-07-15 17:25:42.620273

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1bb036aaf187'
down_revision = 'c2c69e3a858e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('formula', sa.Column('f_yield_unit', sa.String(length=10), nullable=True))
    op.add_column('formula', sa.Column('formula_yield', sa.Float(), nullable=True))
    op.drop_column('formula', 'formula_yeild')
    op.drop_column('formula', 'f_yeild_unit')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('formula', sa.Column('f_yeild_unit', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.add_column('formula', sa.Column('formula_yeild', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('formula', 'formula_yield')
    op.drop_column('formula', 'f_yield_unit')
    # ### end Alembic commands ###
