"""empty message

Revision ID: 29a508b312f1
Revises: 34ee895cd05e
Create Date: 2017-06-25 23:05:50.156793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29a508b312f1'
down_revision = '34ee895cd05e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('formula', sa.Column('date_created', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('user_creator', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'user_creator')
    op.drop_column('formula', 'date_created')
    # ### end Alembic commands ###
