"""empty message

Revision ID: 42ac8e237bb1
Revises: 29a508b312f1
Create Date: 2017-07-02 19:54:41.580696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42ac8e237bb1'
down_revision = '29a508b312f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chemical',
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=80), nullable=True),
    sa.Column('cas', sa.String(length=80), nullable=True),
    sa.Column('user_key', sa.String(length=80), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('beyond_use', sa.Integer(), nullable=True),
    sa.Column('storage', sa.String(length=80), nullable=True),
    sa.Column('explosive', sa.Boolean(), nullable=True),
    sa.Column('flammable', sa.Boolean(), nullable=True),
    sa.Column('oxidizer', sa.Boolean(), nullable=True),
    sa.Column('corrosive', sa.Boolean(), nullable=True),
    sa.Column('toxic', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ingredient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('formula_key', sa.String(length=80), nullable=True),
    sa.Column('ingredient_key', sa.String(length=80), nullable=True),
    sa.Column('step_key', sa.String(length=80), nullable=True),
    sa.Column('step_number', sa.Integer(), nullable=True),
    sa.Column('key', sa.String(length=80), nullable=True),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('product_key', sa.String(length=80), nullable=True),
    sa.Column('product_model', sa.Integer(), nullable=True),
    sa.Column('file_location', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'formula', sa.Column('approved', sa.Boolean(), nullable=True))
    op.add_column(u'formula', sa.Column('beyond_use', sa.Integer(), nullable=True))
    op.add_column(u'formula', sa.Column('cas', sa.String(length=80), nullable=True))
    op.add_column(u'formula', sa.Column('corrosive', sa.Boolean(), nullable=True))
    op.add_column(u'formula', sa.Column('explosive', sa.Boolean(), nullable=True))
    op.add_column(u'formula', sa.Column('flammable', sa.Boolean(), nullable=True))
    op.add_column(u'formula', sa.Column('key', sa.String(length=80), nullable=True))
    op.add_column(u'formula', sa.Column('oxidizer', sa.Boolean(), nullable=True))
    op.add_column(u'formula', sa.Column('prep', sa.String(length=1000), nullable=True))
    op.add_column(u'formula', sa.Column('storage', sa.String(length=80), nullable=True))
    op.add_column(u'formula', sa.Column('time_rq_days', sa.Integer(), nullable=True))
    op.add_column(u'formula', sa.Column('time_rq_hr', sa.Integer(), nullable=True))
    op.add_column(u'formula', sa.Column('time_rq_min', sa.Integer(), nullable=True))
    op.add_column(u'formula', sa.Column('time_rq_sec', sa.Integer(), nullable=True))
    op.add_column(u'formula', sa.Column('toxic', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'formula', 'toxic')
    op.drop_column(u'formula', 'time_rq_sec')
    op.drop_column(u'formula', 'time_rq_min')
    op.drop_column(u'formula', 'time_rq_hr')
    op.drop_column(u'formula', 'time_rq_days')
    op.drop_column(u'formula', 'storage')
    op.drop_column(u'formula', 'prep')
    op.drop_column(u'formula', 'oxidizer')
    op.drop_column(u'formula', 'key')
    op.drop_column(u'formula', 'flammable')
    op.drop_column(u'formula', 'explosive')
    op.drop_column(u'formula', 'corrosive')
    op.drop_column(u'formula', 'cas')
    op.drop_column(u'formula', 'beyond_use')
    op.drop_column(u'formula', 'approved')
    op.drop_table('ingredient')
    op.drop_table('chemical')
    # ### end Alembic commands ###
