"""empty message

Revision ID: ac3e2a73523c
Revises: c69b80425779
Create Date: 2017-07-16 19:05:22.049559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac3e2a73523c'
down_revision = 'c69b80425779'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingredient', sa.Column('ingredient_name', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ingredient', 'ingredient_name')
    # ### end Alembic commands ###
