"""empty message

Revision ID: c2c69e3a858e
Revises: e63abc9b7561
Create Date: 2017-07-15 17:08:35.018302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2c69e3a858e'
down_revision = 'e63abc9b7561'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('formula', sa.Column('d_size_unit', sa.String(length=10), nullable=True))
    op.add_column('formula', sa.Column('dose_form', sa.String(length=50), nullable=True))
    op.add_column('formula', sa.Column('dose_size', sa.Float(), nullable=True))
    op.add_column('formula', sa.Column('f_yeild_unit', sa.String(length=10), nullable=True))
    op.add_column('formula', sa.Column('formula_yeild', sa.Float(), nullable=True))
    op.add_column('ingredient', sa.Column('amount', sa.Float(), nullable=True))
    op.add_column('ingredient', sa.Column('unit', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ingredient', 'unit')
    op.drop_column('ingredient', 'amount')
    op.drop_column('formula', 'formula_yeild')
    op.drop_column('formula', 'f_yeild_unit')
    op.drop_column('formula', 'dose_size')
    op.drop_column('formula', 'dose_form')
    op.drop_column('formula', 'd_size_unit')
    # ### end Alembic commands ###
