"""empty message

Revision ID: c4f3c97b1463
Revises: 1bb036aaf187
Create Date: 2017-07-15 23:38:31.482625

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c4f3c97b1463'
down_revision = '1bb036aaf187'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Instruction',
    sa.Column('formula_key', sa.String(length=80), nullable=True),
    sa.Column('step_number', sa.Integer(), nullable=True),
    sa.Column('step', sa.String(length=1000), nullable=True),
    sa.Column('key', sa.String(length=80), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column(u'ingredient', 'amount',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.drop_column(u'ingredient', 'step_number')
    op.drop_column(u'ingredient', 'step')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'ingredient', sa.Column('step', sa.VARCHAR(length=1000), autoincrement=False, nullable=True))
    op.add_column(u'ingredient', sa.Column('step_number', sa.INTEGER(), autoincrement=False, nullable=True))
    op.alter_column(u'ingredient', 'amount',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.drop_table('Instruction')
    # ### end Alembic commands ###
