"""empty message

Revision ID: c69b80425779
Revises: a9fb4bf2fc11
Create Date: 2017-07-15 23:40:02.417324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c69b80425779'
down_revision = 'a9fb4bf2fc11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attachment',
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_key', sa.String(length=80), nullable=True),
    sa.Column('product_model', sa.Integer(), nullable=True),
    sa.Column('file_location', sa.String(length=80), nullable=True),
    sa.Column('key', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('instruction',
    sa.Column('formula_key', sa.String(length=80), nullable=True),
    sa.Column('step_number', sa.Integer(), nullable=True),
    sa.Column('step', sa.String(length=1000), nullable=True),
    sa.Column('key', sa.String(length=80), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('Instruction')
    op.drop_column(u'ingredient', 'key')
    op.drop_column(u'ingredient', 'file_location')
    op.drop_column(u'ingredient', 'product_model')
    op.drop_column(u'ingredient', 'name')
    op.drop_column(u'ingredient', 'product_key')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'ingredient', sa.Column('product_key', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.add_column(u'ingredient', sa.Column('name', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.add_column(u'ingredient', sa.Column('product_model', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column(u'ingredient', sa.Column('file_location', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.add_column(u'ingredient', sa.Column('key', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.create_table('Instruction',
    sa.Column('formula_key', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('step_number', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('step', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('key', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), server_default=sa.text(u'nextval(\'"Instruction_id_seq"\'::regclass)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=u'Instruction_pkey')
    )
    op.drop_table('instruction')
    op.drop_table('attachment')
    # ### end Alembic commands ###
