"""empty message

Revision ID: e63abc9b7561
Revises: 42ac8e237bb1
Create Date: 2017-07-02 23:53:41.619967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e63abc9b7561'
down_revision = '42ac8e237bb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('formula', 'time_rq_sec')
    op.drop_column('formula', 'cas')
    op.add_column('ingredient', sa.Column('step', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ingredient', 'step')
    op.add_column('formula', sa.Column('cas', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.add_column('formula', sa.Column('time_rq_sec', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
